alleyinteractive/apple-news

- admin/class-admin-apple-index-page.php
- assets/css/export-table.css
- assets/css/settings.css
- includes/apple-exporter/builders/class-component-layouts.php
- includes/apple-exporter/builders/class-layout.php
- includes/apple-exporter/class-workspace.php
- includes/apple-exporter/components/class-cover.php
- tests/exporter/builders/test-class-component-layouts.php
- Fixed some JSON values appearing as strings instead of as strings or integers
- Fixed a JSON encoding issue that was removing newline characters
- Fixed a minor admin CSS issue
> Apple updates

- admin/class-admin-apple-meta-boxes.php
- includes/apple-exporter/components/class-embed-web-video.php
- includes/apple-exporter/components/class-image.php
Setting video aspect ratio to int type. Change args passed to meta box for apple news publishing. Stripping any query arguments in an image filename.
> Post type meta boxes

- admin/partials/page_index.php
Cross check: https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-list-table.php#L326
> adding search input id when passed to WP_List_Table search_box method

- admin/apple-actions/index/class-export.php
Allows for each variable being passed into the Exporter class to be filtered and modified prior to execution.
> adding filter set for content modification prior to export

- includes/apple-exporter/builders/class-components.php
> Adds title component to article.json output

- admin/class-admin-apple-notice.php
- admin/settings/class-admin-apple-settings-section.php
Fixes requested by VIP for deploying the latest release:
- Fixing a warning when saving settings
- Taking advantage of user attributes on VIP for notices
> Async VIP fixes

- admin/settings/class-admin-apple-settings-section.php
- includes/apple-exporter/class-exporter.php
Sorry thought I'd got this one in already!
> Add a filter for fonts list

- admin/apple-actions/index/class-export.php
- admin/partials/page_options.php
- admin/settings/class-admin-apple-settings-section-formatting.php
- admin/settings/class-admin-apple-settings-section.php
- includes/apple-exporter/class-settings.php
Also added the ability to set the field size and required attributes on the Apple News settings page
> Added new field for adjusting byline format

- includes/apple-exporter/components/class-byline.php
- includes/apple-exporter/components/class-cover.php
For consistency, for full width components
> Use register_full_width_layout instead of register_layout

- admin/settings/class-admin-apple-settings-section-formatting.php
- admin/settings/class-admin-apple-settings-section.php
> Resolving some dashboard warnings

- includes/apple-exporter/builders/class-metadata.php
- tests/apple-exporter/builders/test-class-metadata.php
> Added date metadata fields

- admin/apple-actions/index/class-export.php
- includes/apple-exporter/class-exporter.php
- tests/admin/apple-actions/index/test-class-export.php
> Improved auto excerpt functionality

- apple-news.php
> Switching deletion of settings to an uninstall hook

- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-news.php
> Rewriting JSON exports to avoid an ob_start on every page load

- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-news.php
Reverts alleyinteractive/apple-news#141
> Revert "Rewriting JSON exports to avoid an ob_start on every page load"

- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-settings.php
- admin/partials/page_options.php
- admin/settings/class-admin-apple-settings-section-formatting.php
- admin/settings/class-admin-apple-settings-section-post-types.php
- admin/settings/class-admin-apple-settings-section.php
- includes/apple-push-api/request/class-request.php
- includes/class-apple-news.php
> Refactor options to use a single serialized value and migrate options from previous plugin versions to new format

- admin/class-admin-apple-meta-boxes.php
- admin/class-admin-apple-post-sync.php
> Fixed bug with manual publish button

- admin/class-admin-apple-index-page.php
> Fixed issue with bottom menu on bulk actions

- README.md
- admin/apple-actions/index/class-push.php
- admin/apple-actions/index/class-section.php
- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-meta-boxes.php
- admin/class-admin-apple-news-list-table.php
- admin/class-admin-apple-post-sync.php
- admin/partials/page_single_push.php
- admin/partials/page_single_settings.php
- admin/settings/class-admin-apple-settings-section.php
- apple-news.php
- assets/css/meta-boxes.css
- includes/apple-push-api/class-api.php
- includes/apple-push-api/request/class-request.php
- includes/class-apple-news.php
- readme.txt
- tests/admin/apple-actions/index/test-class-push.php
> Adding the ability to publish to multiple sections and designate a post as a preview

- README.md
- admin/apple-actions/index/class-section.php
- admin/class-admin-apple-index-page.php
- admin/settings/class-admin-apple-settings-section-advanced.php
- apple-news.php
- includes/class-apple-news.php
- readme.txt
Also incrementing plugin to 1.1.2 to force updates and adding release notes.
> Fixing fatal error when trying to load Apple News list before entering channel details

- admin/settings/class-admin-apple-settings-section-formatting.php
- includes/apple-exporter/builders/class-components.php
- includes/apple-exporter/class-exporter.php
- includes/apple-exporter/class-settings.php
- includes/apple-exporter/components/class-byline.php
- includes/apple-exporter/components/class-cover.php
- tests/apple-exporter/builders/test-class-components.php
Also add custom background color support
> Fix parallax text issues

- admin/apple-actions/index/class-export.php
- tests/admin/apple-actions/index/test-class-export.php
> Fixed incorrect parsing of bylines with a hashtag in the name, added unit tests for byline format

- includes/apple-push-api/request/class-request.php
> Enhanced debug email format

- README.md
- admin/apple-actions/index/class-push.php
- admin/class-admin-apple-meta-boxes.php
- admin/class-admin-apple-notice.php
- apple-news.php
- assets/css/meta-boxes.css
- includes/apple-push-api/request/class-request.php
- includes/class-apple-news.php
- readme.txt
> Vastly improved error messages from the API

- admin/class-admin-apple-post-sync.php
- apple-news.php
- includes/class-apple-news.php
- readme.txt
Refactors logic for skipping permission check correctly.
Fixes #116
> Releasing hotfix version 1.1.7

- admin/class-admin-apple-meta-boxes.php
- apple-news.php
- includes/class-apple-news.php
- readme.txt
- tests/admin/test-class-admin-apple-meta-boxes.php
Also adds unit test for meta box class
Incrementing to version 1.1.8 to force update
Fixes #226
> Fixed bug with saving meta box values with auto sync enabled

- admin/class-admin-apple-settings.php
- admin/settings/class-admin-apple-settings-section.php
- assets/css/settings.css
- assets/js/settings.js
This will only work on Macs, but looks great for those users!
Closes #245
> Added custom font display to font select dropdowns

- admin/apple-actions/index/class-export.php
- admin/partials/page_options.php
- admin/settings/class-admin-apple-settings-section-formatting.php
- admin/settings/class-admin-apple-settings-section.php
- assets/css/settings.css
- assets/js/settings.js
- readme.txt
This enables a web preview that gives an approximate representation in HTML of what your Apple News settings will look like in Apple News.
Closes #243
> Web preview

- includes/apple-exporter/builders/class-components.php
- includes/apple-exporter/components/class-cover.php
* Replaces hardcoded column span values with dynamic values from the settings object.
Fixes #262.
> AN-55 Center container width fix

- includes/apple-exporter/builders/class-components.php
* Adds functionality to group body elements intelligently instead of greedily to provide more breaks between body components to allow for ad placement.
* Refactors class-components.php to conform to WordPress standards and PHP best practices.
> AN-55 Intelligent content grouping for body elements

- admin/apple-actions/index/class-push.php
- includes/apple-push-api/class-api.php
- includes/apple-push-api/request/class-request.php
- tests/admin/apple-actions/index/test-class-push.php
> Added new parameter to filters for post requests

- includes/apple-exporter/class-parser.php
- tests/apple-exporter/test-class-parser.php
Also removes anchors, which are not valid in Apple News.
Also adds corresponding unit tests.
Closes #148
> Fixes handling of relative URLs in the post body

- admin/class-admin-apple-bulk-export-page.php
- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-news-list-table.php
- assets/js/export-table.js
- phpunit.xml
- tests/admin/test-class-admin-apple-index-page.php
Also added delete confirmation dialog and corresponding unit tests.
Closes #117
> Added ability to reset stuck posts

- admin/apple-actions/index/class-delete.php
- admin/class-admin-apple-post-sync.php
- admin/class-admin-apple-settings.php
- admin/settings/class-admin-apple-settings-section-api.php
- includes/apple-exporter/class-settings.php
- includes/class-apple-news.php
Also refactored code for migrating settings.
Closes #147
> Separating control over auto deletion to a new setting

- includes/apple-exporter/class-component-factory.php
- includes/apple-exporter/components/class-facebook.php
- tests/apple-exporter/components/test-class-facebook.php
* Adds support for Facebook embeds using oEmbed format.
* Adds unit test coverage for Facebook embeds for each supported oEmbed format.
Fixes #188.
> AN-46 Adding support for Facebook embeds

- admin/class-admin-apple-themes.php
- admin/settings/class-admin-apple-settings-section-formatting.php
- assets/css/preview.css
- assets/css/theme-edit.css
- assets/js/preview.js
- assets/js/theme-edit.js
- tests/apple-exporter/builders/test-class-components.php
* Adds support for making elements in the component order inactive.
* Updates unit tests for meta components to support removed meta components.
* Updates theme import rules to allow for inactive components.
Fixes #151.
> AN-64 Adding support for making certain components inactive

- includes/apple-exporter/class-component-factory.php
- includes/apple-exporter/components/class-body.php
- tests/apple-exporter/components/test-class-body.php
* Adds support for nested images in lists (ol and ul).
* Adds mappings for list types and `<pre>` tags to the body class for handling.
* Adds test coverage for nested images in lists.
Fixes #129.
> AN-65 Adding support for nested images in lists

- .travis.yml
* Explicitly fixes the PHPUnit version (depending on PHP version) to avoid incompatibility with PHPUnit 6.
> Fix for PHPUnit version used on Travis

- admin/class-admin-apple-async.php
- admin/class-admin-apple-bulk-export-page.php
- admin/class-admin-apple-index-page.php
- admin/class-admin-apple-json.php
- admin/class-admin-apple-meta-boxes.php
- admin/class-admin-apple-news-list-table.php
- admin/class-admin-apple-news.php
- admin/class-admin-apple-post-sync.php
- admin/class-admin-apple-preview.php
- admin/class-admin-apple-sections.php
- admin/class-admin-apple-settings.php
- admin/class-admin-apple-themes.php
- admin/settings/class-admin-apple-settings-section.php
- apple-news.php
- includes/apple-exporter/builders/class-component-layouts.php
- includes/apple-exporter/builders/class-components.php
- includes/apple-exporter/class-component-spec.php
- includes/apple-exporter/class-exporter.php
- includes/apple-exporter/class-workspace.php
- includes/apple-exporter/components/class-audio.php
- includes/apple-exporter/components/class-body.php
- includes/apple-exporter/components/class-component.php
- includes/apple-exporter/components/class-divider.php
- includes/apple-exporter/components/class-embed-web-video.php
- includes/apple-exporter/components/class-image.php
- includes/apple-exporter/components/class-tweet.php
- includes/apple-push-api/class-mime-builder.php
- includes/apple-push-api/request/class-request.php
- tests/admin/test-class-admin-apple-json.php
- tests/admin/test-class-admin-apple-meta-boxes.php
* Ensures the strict parameter is used on all `in_array` calls.
* Ensures all translation functions inside of `wp_die` calls are escaped.
* Ensures all instances of `==` are converted to `===`.
* Ensures all instances of `!=` are converted to `!==`.
* Ensures all instances of `json_encode` are converted to `wp_json_encode`.
* Adds some additional escaping.
* Cleans up code in the immediate vicinity of updates in a few instances.
> AN-17 Addressing VIP feedback

- apple-news.php
- includes/class-apple-news.php
- readme.txt
* Updates version code and stable tag to 1.2.6.
* Updates changelog to reflect updates in this version.
> AN-17 Bumping version to 1.2.6 and updating changelog

- apple-news.php
- includes/class-apple-news.php
- readme.txt
* Bumps the version number from 1.2.7 to 1.3.0
* Updates the changelog
> Preparing version 1.3.0

- admin/class-admin-apple-themes.php
- includes/apple-exporter/class-component-spec.php
- tests/apple-exporter/components/class-component-testcase.php
- tests/apple-exporter/components/test-class-body.php
- tests/apple-exporter/components/test-class-byline.php
- tests/apple-exporter/components/test-class-heading.php
- tests/apple-exporter/components/test-class-quote.php
* Fixes a bug where select menus don't display properly in the theme editor.
* Fixes a bug where tokens with values that are falsey would not get replaced.
* Fixes a bug where tokens that are conditionally included would not get removed if not present in the values array.
* Adds unit test coverage to check for unreplaced tokens in component JSON.
> 1.3.0 bugfixes

- readme.txt
* Add information about bugfix for HTML in titles.
* Properly escape < and > in readme to fix display issues.
> AN-17 Update release notes for version 1.3.0

- admin/apple-actions/index/class-export.php
Prevent `<style>` tags and any CSS within them from being published within the Apple News body or excerpt
Fixes #377
> AN-88 Remove style tags and their contents

- admin/apple-actions/index/class-push.php
- admin/class-admin-apple-meta-boxes.php
- admin/partials/metabox_publish.php
- admin/partials/page_single_push.php
- includes/apple-exporter/class-exporter.php
- includes/apple-exporter/class-theme.php
These changes add support for setting the isHidden flag on publish and update calls, and adds a metabox option to toggle isHidden.
> Adding support for isHidden.

- admin/apple-actions/index/class-export.php
- includes/apple-exporter/class-exporter-content.php
- includes/apple-exporter/class-markdown.php
- includes/apple-exporter/class-parser.php
- includes/apple-exporter/components/class-facebook.php
- includes/apple-exporter/third-party/class-jetpack-tiled-gallery.php
- tests/admin/apple-actions/index/test-class-export.php
- tests/apple-exporter/components/test-class-facebook.php
- tests/apple-exporter/test-class-parser.php
This PR simply merges four previously approved PRs into `master` from a separate branch related to the 1.4 release.
> Roll up four 1.4 features into master

- includes/apple-exporter/class-parser.php
- tests/admin/apple-actions/index/test-class-push.php
- tests/apple-exporter/components/class-component-testcase.php
- tests/apple-exporter/test-class-parser.php
* Revise link handling to address several edge cases of empty or malformed URLs, properly handle root-relative URLs, and properly handle anchor links.
* Add test cases to check each of these.
* Fix tests as a result of a previous PR that sets defaults for `isPreview` etc.
> AN-92 Link refinements

- includes/apple-exporter/components/class-component.php
- tests/apple-exporter/components/test-class-body.php
* Add new filter for turning HTML support on or off on a per-component basis.
* Add a test for the filter.
> AN-94 Add filter for HTML support on a per-component basis

- includes/apple-exporter/class-theme.php
- includes/apple-exporter/components/class-table.php
* Add component JSON to the Table component to include table styles.
* Modify fields for table style to only have one option for border, since the styling capabilities in Apple News Format make it difficult to separate borders for headers and normal cells.
> AN-129 Wire up table display settings to output JSON

- admin/class-admin-apple-preview.php
- assets/css/preview.css
- assets/js/preview.js
* Adds live preview functionality for table settings, if HTML support is enabled.
> AN-129 Table style preview

- admin/class-admin-apple-sections.php
> AN-96 Swap deprecated wpcom_vip functions for core versions

- admin/class-admin-apple-preview.php
- admin/partials/page_single_push.php
- includes/class-apple-news.php
> AN-97 Fix undefined index and undefined variable notices

- includes/apple-push-api/request/class-request.php
> AN-98 Fix undefined message warning if article deleted from iCloud

- includes/apple-exporter/class-theme.php
- tests/apple-exporter/test-class-theme.php
> AN-105 Re-add apple_news_fonts_list hook

- admin/apple-actions/index/class-export.php
- apple-news.php
- tests/admin/apple-actions/index/test-class-export.php
> AN-114 Add function for determining whether an export is happening

- includes/apple-exporter/class-theme.php
> AN-110 Add handling for empty meta_component_order in theme edit

- admin/class-admin-apple-bulk-export-page.php
- admin/class-admin-apple-post-sync.php
- admin/partials/metabox_publish.php
- includes/class-apple-news.php
> AN-109 Align Apple News publish and delete caps with WP publish and delete caps

- admin/class-admin-apple-sections.php
- admin/partials/page_sections.php
- assets/js/sections.js
> AN-117 Add refresh sections button on the Sections page

- .travis.yml
- bin/install-wp-tests.sh
* Make WordPress nightly required to pass.
* Revert to using bash script to install WordPress.
> AN-101 Travis refinements

- admin/class-admin-apple-post-sync.php
Request: add in the ability to disable post auto-publishing on a per-post level.
> Adding in a filter to disable auto-publishing on a per-post level

- admin/class-admin-apple-meta-boxes.php
> Bail early when nonce isn't present, to avoid breaking Quick Edit

- readme.txt
* Adds changelog items for earlier changes made by @srtfisher
> Add additional changelog items

- includes/apple-push-api/request/class-request.php
allows users to specify sender of notification emails
> add apple_news_notification_headers filter

- admin/class-admin-apple-news.php
- admin/class-admin-apple-notice.php
- apple-news.php
- assets/js/pluginsidebar/components/notifications/index.js
- assets/js/pluginsidebar/components/sidebar/index.js
- includes/REST/apple-news-clear-notifications.php
- includes/REST/apple-news-get-notifications.php
- includes/class-apple-news.php
- includes/meta.php
- package-lock.json
- package.json
* Add handler for notices in Gutenberg.
* Disable normal notice handling when Gutenberg is active.
* General cleanup/organization from the last round of changes.
> AN-158 Add handling for notices in Gutenberg

- .babelrc
- assets/js/pluginsidebar/components/sidebar/index.js
- assets/js/util/safeJsonParse.js
- assets/js/util/safeJsonParse.spec.js
- assets/js/util/safeJsonParseArray.js
- assets/js/util/safeJsonParseArray.spec.js
- assets/js/util/safeJsonParseObject.js
- assets/js/util/safeJsonParseObject.spec.js
* Add type checking
* Add fallbacks
* Prevent SyntaxErrors from being thrown
* Add tests
> AN-198 Add util functions for safely parsing JSON data

- admin/settings/class-admin-apple-settings-section-api.php
Allows users to see entire contents of IDs.
> Increase length of API Channel, API Key and API secret fields
