alleyinteractive/apple-news

includes/apple-exporter/components/class-tweet.php
Update to match url with a trailing slash, extended resource path, and allow for a soft returns before the URL. Referencing WP:
https://github.com/WordPress/WordPress/blob/master/wp-includes/class-oembed.php#L57
=> Regex update to match node for twitter

admin/settings/class-admin-apple-settings-section.php
makes sure the key for a default value exists before trying to retrieve and return it
=> updating default retrieval to check for it's existence first

admin/apple-actions/index/class-push.php, admin/class-admin-apple-async.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-news.php, admin/class-admin-apple-notice.php, admin/settings/class-admin-apple-settings-section-api.php, admin/settings/class-admin-apple-settings-section.php, apple-news.php, includes/apple-exporter/class-settings.php, includes/class-apple-news.php
This update adds a major feature to Apple News, asynchronous publishing. The intent is that push actions can be offloaded to a single scheduled event so the editor is not forced to wait for a massive push request to finish.
On WordPress VIP, this will automatically use the Jobs system which has a very high max execution time and therefore will avoid timeouts for articles with lots of images that often take longer than 30 seconds to publish to Apple News.
This also adds a minor feature to allow for descriptions for individual settings, required to explain this feature. It also confidently brands this as a 1.0.0 release as this is the last major lacking component.
=> Asynchronous publishing

includes/apple-exporter/components/class-component.php
Small maintenance patch to catch a potential fatal error if the `remote_file_exists` check returns a `WP_Error`
=> Don't fatal if remote file fetch returns WP_Error

admin/apple-actions/index/class-push.php
We need to prevent some posts from getting pushed to apple. These may be sponsored posts, or contain embeds that are not supported.
We've been making use of the `apple_news_is_post_in_sync` filter to do this - but its really not intended for this. 
We could simply add a filter in the `Push:push` method to allow a single post to be skipped.
I'm interested in hearing your thoughts - there may be a better way to tackle this.
=> Add filter for skipping push

admin/apple-actions/index/class-export.php, admin/apple-actions/index/class-push.php
One issue we've been running into is that we need to modify the content only within the context of an apple news post.
For example we wish to completely remove/modify some shortcodes that aren't relevant. If we have a way we can do stuff immediately before the content is generated, we can easily do this.
Currently we can are abusing some of the existing filters, but isn't very nice. This new action follows a similar pattern to the `apple_news_before_push` action.
=> Add filter before generate content

includes/apple-exporter/components/class-embed-web-video.php
I get the following error embedding a video from Vimeo: 
>Error: The URL, [https://player.vimeo.com/video/], is invalid. Please see documentation for more details >about embedded video.
>document -> components -> [3]
The generated component looks like this: 
```js
{
"role": "embedwebvideo",
"aspectRatio": 1.777,
"URL": "https://player.vimeo.com/video/"
}
```
Note the ID is missing from the URL. 
This bug is caused by referencing the wrong match from the regex.
For reference - this is the Vimeo regex:
`'#^https?://(?:.+\.)?vimeo\.com/(:?.+/)?(\d+)$#'`
=> Fix - Vimeo embeds broken

includes/apple-exporter/components/class-embed-web-video.php
Remove iFrame video embed handler as its causing problems and is no longer supported. See https://github.com/alleyinteractive/apple-news/issues/45
Also fixes bit of an odd issue with embeds like: `youtu.be.com/$id` not finding the video ID. Basically need to wrap the tertiary operator for grabbing the ID in parentheses.
Consider the following code: 
```
$x = ''; 
$y = 'bar'; 
echo $x ?: $y; // echos 'bar';
echo 'foo-' . $x ?: $y; // echos 'foo-';
echo 'foo-' . ( $x ?: $y ); // echos 'foo-bar';
```
=> Improve video

includes/apple-exporter/class-markdown.php
Currently comments are treated as text nodes, meaning the contents of the comment get displayed as if it were normal text (with the comment tags stripped). Instead, this removes comments altogether.
=> Remove comments from parsed markdown

admin/class-admin-apple-async.php
The async_push is running either in WP_Cron or in Jobs system on the WordPress.com VIP platform. In both cases, the current_user_id is 0 and thus Notices about failures are not being properly saved either to user_meta or user_attributes
=> Pass $user_id to Admin_Apple_Notice::error method

admin/apple-actions/index/class-push.php
Pending and in progress post metas are removed only in case the post is successfully published. That's preventing users from re-publishing their posts in case something goes wrong.
I'm not moving the metas to clean_workspace method as that one is also called early within the try block.
=> Always remove penging and async_in_progress metas

admin/apple-actions/index/class-push.php
We have some custom code hooked into the clean_workspace actions that triggers correctly during pushing to Apple, but if an exception is thrown, it's not called.
PR adds clean_workspace into the exception catch block.
=> When pushing, clean workspace if an exception is thrown.

includes/apple-exporter/class-exporter.php
We have some custom code hooked into the `clean_workspace()` function's actions. The `clean_workspace()` is called before and after the `push` action correctly, but for `export` action it's only called before the action. To be consistent, we need to cleanup after the `export` action too.
PR adds `clean_workspace()` after the `export` action is performed.
=> Cleanup the workspace after the export action is executed

includes/apple-exporter/builders/class-metadata.php
As recommended by Apple News this [improves share-ability](https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Metadata.html#//apple_ref/doc/uid/TP40015408-CH3-SW1). An article is displayed on other devices that don't support Apple News **if** canonical URL is specified.
=> Add canonical URL to the article metadata

includes/apple-exporter/components/class-instagram.php
1. After the Instagram URL has been processed by embed into the blockquote, the URL seems to have `www` even if original URL didn't. Allow for optional `www.` in the URL as it's valid - so we actually match it.
2. However, according to [AN docs](https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Instagram.html#//apple_ref/doc/uid/TP40015408-CH22-SW1), they don't allow `www` in their parser, so remove `www.` in the AN json markup.
=> Fix matching of Instagram URL, so component is generated correctly

includes/apple-exporter/components/class-embed-web-video.php
A dash is a valid character in a YouTube identifier - this wasn't being matched by the \w character.
The plugin also wasn't matching YouTube URLs which had other query parameters which are sometimes present - eg:
https://www.youtube.com/watch?v=xxxxxxx&feature=youtu.be
This could possibly be fixed by removing the $ from the regex, but have used [^ ] so it allows any non-space character, just to prevent a match in the rare cases there was a space followed by a paragraph of text.
=> Matching dashes and extra query parameters in YouTube URLs

includes/apple-push-api/request/class-request.php
You can specify a variety of API request meta before pushing to Apple News - [docs example](https://developer.apple.com/library/ios/documentation/General/Conceptual/News_API_Ref/CreateArticle.html#//apple_ref/doc/uid/TP40015409-CH14-SW11).
You can specify, for example, links -> sections, so that a post is published in the channel by default and also in the specified sections. Currently, there is no way to add custom meta to request.
Feel free to rename the filter name if required.
=> Add filter to API request meta

includes/apple-exporter/builders/class-components.php
currently an export or publish action for Apple News will fail if there is a missing component in the `anchor_components` functions. this adds a check to ensure it is there before proceeding.
=> adding check for component with index variable

apple-news.php
If the plugin is loaded due a cron process - for example, when a scheduled post is published, or the async method is used - everything dies with a php error because the get_plugin_data function does not exist.
=> Ensure get_plugin_data function exists before using it

composer.json
Allows people to utilize `composer` to add, install, and update the plugin from the source repo.
=> Add installer compatibility to composer.json

admin/apple-actions/index/class-push.php, admin/class-admin-apple-meta-boxes.php, admin/settings/class-admin-apple-settings-section-api.php, includes/apple-exporter/class-settings.php, tests/admin/apple-actions/index/test-class-push.php
- Always showing the Apple News meta box so settings can be added prior to publish
- Showing the Apple News meta box by default
- Never passively sending `isPreview=false` to the API
Fixes #210
=> Meta box and API updates

admin/settings/class-admin-apple-settings-section-formatting.php, includes/apple-exporter/class-component-factory.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/components/class-pre.php, tests/apple-exporter/components/test-class-pre.php
This is specifically for `<pre>` blocks, as they were previously stripped out entirely of articles, making for awkward reading of a tech article that includes them.
I'm no pro at this, so I have no idea if this PR is up-to-snuff.
I did however test it in production and it WorksForMe.
Settings:
Example article of a pre tag making it all the way to production Apple News:
Fixes #222
=> New component to handle `<pre>` tags

admin/class-admin-apple-settings.php, admin/settings/class-admin-apple-settings-section.php, assets/js/settings.js, includes/apple-exporter/class-settings.php
This offers wider browser compatibility than using an HTML color field.
Closes #244
=> Use WP built-in color picker

admin/apple-actions/class-action-exception.php, admin/apple-actions/class-action.php, admin/apple-actions/class-api-action.php, admin/apple-actions/index/class-export.php, admin/apple-actions/index/class-push.php, admin/class-admin-apple-notice.php, admin/settings/class-admin-apple-settings-section-advanced.php, includes/apple-exporter/class-exporter.php, includes/apple-exporter/class-settings.php, includes/class-apple-news.php, tests/admin/apple-actions/index/test-class-push.php, tests/admin/test-class-admin-apple-notice.php, tests/test-class-apple-news.php
1. Creates a framework for JSON validation and initially introduces checking for unicode character sequences that are symptomatic of display issues that have been witnessed, though not reproduced, in Apple News.
2. Breaks out Action_Exception into its own class file for cleanliness.
3. Adds direct support links to every error message.
4. Adds better formatting of multiple error messages.
5. Adds unit tests for the Apple_News and Admin_Apple_Notice classes
6. Adds new unit tests for Push
Closes #146
=> Add JSON error handling

.gitignore, admin/class-admin-apple-bulk-export-page.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-meta-boxes.php
* Fixes a warning that arises when trying to access static class methods using arrow syntax.
=> Bugfix for static asset versioning

includes/apple-exporter/builders/class-builder.php, includes/apple-exporter/builders/class-component-layouts.php, includes/apple-exporter/class-exporter-content.php, includes/apple-exporter/class-settings.php
* Sets the body text column span on non-center aligned layouts to be the same as the number of columns so that the text goes edge-to-edge.
* Fixes the logic for positioning images in centered and non-centered layouts to prevent bleed-over from the margins on non-centered layouts.
* Refactors the following classes for adherence to WordPress standards and PHP best practices:
* Apple_Exporter\Builders\Builder
* Apple_Exporter\Settings
Fixes #233.
=> AN-55 Fix for widescreen text width

includes/class-apple-news.php, tests/apple-exporter/components/test-class-heading.php
* Fixes a bug in which the legacy header settings get stuck in options and are not removed.
* Adds test coverage for the legacy header settings migration function.
=> AN-53 Legacy header settings fix

admin/settings/class-admin-apple-settings-section-advanced.php, admin/settings/class-admin-apple-settings-section-formatting.php, assets/js/settings.js, includes/apple-exporter/builders/class-text-styles.php, includes/apple-exporter/class-exporter.php, includes/apple-exporter/class-html.php, includes/apple-exporter/class-markdown.php, includes/apple-exporter/class-parser.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/class-workspace.php, includes/apple-exporter/components/class-body.php, includes/apple-exporter/components/class-component.php, includes/apple-exporter/components/class-heading.php, includes/apple-exporter/components/class-quote.php, tests/apple-exporter/components/test-class-body.php
* Adds HTML support option in the Settings area.
* Adds HTML support to Body elements if enabled in Settings.
* Adds a new Parser class to handle the split between Markdown and HTML.
* Refactors the Markdown class to conform to WordPress and PHP best practices.
* Expands definition of Body elements to include `<pre>` tags.
* Adds settings for monospaced font display.
* Adds global styles for monospaced fonts if HTML is enabled.
* Adds tests for HTML in Body elements.
Fixes #222.
Fixes #232.
=> AN-54 Addition of basic HTML support

admin/settings/class-admin-apple-settings-section-formatting.php, apple-news.php, assets/js/settings.js, includes/apple-exporter/builders/class-component-layouts.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/components/class-body.php, includes/apple-exporter/components/class-component.php, includes/apple-exporter/components/class-heading.php, includes/apple-exporter/components/class-image.php, includes/class-apple-news.php, readme.txt
* Changes the nomenclature for "body alignment" to "body orientation" and adds description text making the behavior clear.
* Adds a column of margin on the right for left orientation and a column of margin on the left for right orientation.
* Changes behavior of headings on center orientation to be aligned to the left side of body text.
* Version bump to 1.2.1 and relevant additions to changelog.
=> AN-56 Final tweaks and version bump

admin/apple-actions/index/class-push.php, admin/class-admin-apple-async.php, tests/admin/apple-actions/index/test-class-push.php
* Moved successful publish message to Push class.
* Split verbiage of success message based on whether the article was updated or published for the first time.
Fixes #278.
=> AN-17 Refinement of successful push message

admin/settings/class-admin-apple-settings-section-formatting.php, assets/css/settings.css, assets/js/settings.js, includes/apple-exporter/builders/class-components.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/components/class-quote.php, includes/class-apple-news.php, tests/apple-exporter/components/test-class-quote.php, tests/test-class-apple-news.php
* Created a new settings block for blockquote-specific settings.
* Changed behavior and appearance of blockquotes to differentiate them from pullquotes.
* Created a settings migration function to use existing body and pullquote settings to initialize blockquote settings.
* Added reusable functions for handling settings migration in the base Apple_News class.
* Refactored test-apple-news.php to conform to WordPress coding standards and PHP best practices.
* Added unit test coverage in test-apple-news.php to cover all settings migration functions.
* Added unit test coverage for blockquotes.
Fixes #246.
=> AN-59 Split pullquote and blockquote styling

admin/apple-actions/index/class-push.php, admin/apple-actions/index/class-section.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-meta-boxes.php, admin/class-admin-apple-news.php, admin/class-admin-apple-preview.php, admin/class-admin-apple-sections.php, admin/class-admin-apple-settings.php, admin/class-admin-apple-themes.php, admin/partials/page_sections.php, admin/partials/page_single_push.php, assets/css/sections.css, assets/js/meta-boxes.js, assets/js/sections.js, assets/js/single-push.js, tests/admin/test-class-admin-apple-sections.php, tests/admin/test-class-admin-apple-themes.php
* Adds a new settings screen called Sections.
* Allows for mapping taxonomy terms to sections for automatic section assignment.
* Adds an override checkbox if mappings are enabled to allow for overriding section assignments on a per-post basis.
* Adds unit test coverage for the new functionality.
Fixes #167.
=> AN-57 Taxonomy/section mappings

includes/apple-exporter/components/class-gallery.php, tests/apple-exporter/components/test-class-gallery.php
* Adds support for captions on images in galleries.
* Adds support for alt text on images in galleries.
* Adds a unit test for complex galleries including both captions and alt text.
* Refactors the `Gallery` and `Gallery_Test` classes for adherence to WordPress standards and PHP best practices.
Fixes #97.
=> AN-24 Adding support for gallery captions

includes/apple-exporter/builders/class-builder.php, includes/apple-exporter/builders/class-metadata.php, includes/apple-exporter/components/class-video.php, tests/apple-exporter/builders/test-class-metadata.php, tests/apple-exporter/components/test-class-video.php
* Added support for the `stillURL` property on `video` elements.
* Refactored the `Video_Test` class to conform to WordPress standards and PHP best practices.
* Bugfix for mismatched video URLs in metadata and `video` elements when a query string is present.
* Added central `maybe_bundle_source` function to `Builder` class for more streamlined handling of image bundling in metadata.
=> AN-43 Adding support for still URLs in video elements

includes/apple-exporter/class-exporter.php
* Replaces Unicode separator characters with spaces.
* Replaces two or more spaces with a single space.
* Resolves error messages and display issues related to the use of Unicode separator characters, including non-breaking spaces.
Fixes #271
=> AN-17 Fix for encoding warning with Unicode separator characters

admin/class-admin-apple-news.php, admin/partials/cover_art.php, assets/js/cover-art.js, tests/apple-exporter/builders/test-class-metadata.php
* Added detail to the language describing how to use the cover art feature.
* Removed additional image crop sizes. Only the largest image size will be provided to Apple News, and additional crops will be handled by the Apple News service.
=> AN-45 Cover art refinements

admin/class-admin-apple-preview.php, admin/settings/class-admin-apple-settings-section-formatting.php, admin/settings/class-admin-apple-settings-section.php, assets/css/preview.css, assets/js/preview.js, assets/js/theme-edit.js, includes/apple-exporter/class-settings.php, includes/apple-exporter/components/class-body.php, tests/apple-exporter/components/test-class-body.php
* Adds support for configurable background color, number of characters, number of lines, number of raised lines, and padding to dropcap settings.
* Adds preview support for the new settings.
* Adds unit test coverage for the new settings.
* Fixes a display bug where new values in the color picker don't take effect right away.
* Fixes a bug in which numerical settings with a valid value of `0` are overwritten by the default on save.
Fixes #247.
=> AN-63 Adding support for additional drop cap style options

includes/apple-exporter/components/class-instagram.php, tests/apple-exporter/components/test-class-instagram.php
* Adds support for Instagram oEmbed strings in addition to the full embed support already present.
* Refactors the Instagram component class and test class to conform to WordPress standards and PHP best practices.
Fixes #261.
=> AN-17 Adds support for Instagram oEmbed strings

admin/partials/page_theme_edit.php
* Adds page title in an H1 to the theme edit page for semantic HTML best practices and to ensure that admin notices display in the proper location.
Fixes #300.
=> AN-17 Adding H1 to theme edit page

includes/apple-exporter/builders/class-components.php
* Fix for edge case where the cover is set to inactive and there is no featured image set, whereby the first image is erroneously removed from the body content.
=> AN-64 Fix for images being removed from body when cover is inactive

admin/apple-actions/class-api-action.php, tests/admin/apple-actions/index/test-class-export.php, tests/admin/test-class-admin-apple-meta-boxes.php, tests/admin/test-class-admin-apple-sections.php
> All News API requests should be issued against the URL https://news-api.apple.com.
The [official API docs](https://developer.apple.com/library/content/documentation/General/Conceptual/News_API_Ref/index.html) say requests should be sent to https://news-api.apple.com/ - I can't find any reference to the digitalhub.com URL.
=> Use API URL from official documentation

tests/admin/apple-actions/index/test-class-push.php, tests/apple-push-api/test-class-api.php
* Replaces last reference to digitalhub.com with news-api.apple.com
* Ensures all API URLs are https
=> Cleans up API URLs

admin/class-admin-apple-news.php, admin/class-admin-apple-sections.php
* Adds a generic function for printing error messages within the admin.
* Converts the `wp_die()` call which fires when the plugin is unable to fetch a list of sections from the API to use the non-fatal generic function for printing error messages to the user.
Fixes #341.
=> Converting sections API error into a non-fatal

admin/class-admin-apple-settings.php, admin/settings/class-admin-apple-settings-section-developer-tools.php, assets/js/settings.js
* Makes administrator email field on the settings page required only when debug is enabled.
* Cleans up developer settings section class to adhere to WordPress coding standards.
Fixes #342.
=> Making administrator email requirement conditional

admin/class-admin-apple-news.php, apple-news.php, includes/class-apple-news.php, readme.txt
* Updates version number to 1.2.5
* Updates release notes for bugfixes introduced in this version
* Adds a `@since` parameter for a function introduced in this version
=> Version 1.2.5 version bump and release notes

README.md, readme.txt
* Proper spacing after subheading in readme.txt
* Added minor version in "tested up to"
* Added spacing after `#` to produce proper headings in README.md
=> README cleanup for version 1.2.5

includes/apple-exporter/builders/class-metadata.php, includes/apple-exporter/class-exporter-content.php, includes/apple-exporter/components/class-audio.php, includes/apple-exporter/components/class-component.php, includes/apple-exporter/components/class-gallery.php, includes/apple-exporter/components/class-image.php, includes/apple-exporter/components/class-video.php, tests/apple-exporter/components/test-class-image.php
* Adds support for root-relative URLs for audio, images, and videos.
* Adds additional checks on image sources to ensure they are valid.
* Prevents images from being added with empty URLs.
* Adds test coverage for empty image sources, fragment sources, and root-relative sources for images.
Fixes #316.
Fixes #351.
=> AN-17 Expanding media source support

admin/apple-actions/index/class-push.php, admin/class-admin-apple-themes.php, apple-news.php, includes/apple-exporter/components/class-component.php, includes/class-apple-news.php, readme.txt
Fixes #352 where HTML tags are being stripped when pushed to the API.
Fixes #362 to ensure backwards compatibility with older theme files when new formatting settings are added.
=> Hotfixes for urgent issues

admin/class-admin-apple-themes.php, admin/partials/page_themes.php, assets/js/themes.js, includes/class-apple-news.php
* Moves the example theme load functionality to a standalone function.
* Adds a button to load example themes on the Themes page.
* Adds descriptive text about the new example themes to the Themes page.
=> AN-78 Adds a button to load example themes on demand

includes/apple-exporter/class-theme.php, tests/apple-exporter/test-class-theme.php
* Sorts theme registry when retrieved, added to, or removed from.
* Ensures the active theme is first, followed by the rest of the themes in alphabetical order.
* Adds test coverage for retrieving a sorted theme list.
=> AN-78 Adds sort to theme registry

admin/class-admin-apple-themes.php
* Informs users (via an admin notice on Publish to Apple News admin screens) that example themes are available for installation on the Themes screen.
* This nag will be removed in a future version, similar to what we did when we moved theme settings to the separate themes page.
=> AN-78 Adds a nag for example themes to Apple News admin screens

includes/apple-exporter/class-exporter.php, includes/apple-exporter/components/class-title.php, tests/apple-exporter/components/test-class-title.php
* Explicitly sets the format for the title component to HTML to support HTML in titles.
* Adds wp_strip_all_tags to the main document title to remove any HTML tags that may have been added.
* Adjusts unit tests accordingly.
Addresses https://wordpress.org/support/topic/solution-apple-news-formatting-problems-with-exposed-html/.
=> AN-17 Add support for HTML in titles

admin/class-admin-apple-themes.php, includes/apple-exporter/class-theme.php, includes/class-apple-news.php
* Establishes type juggling on values loaded on themes.
* Performs a check on theme settings that doesn't throw a Notice.
* Standardizes calls to get_options to always use static calls.
Fixes #407.
=> Fixes PHP notices on the Themes interface

includes/apple-exporter/components/class-heading.php, tests/apple-exporter/components/test-class-heading.php
* Fixes a bug whereby an image wrapped in a link wrapped in a heading tag triggers an empty text node for the heading, which causes an error when publishing to Apple News.
* Adds a test case to validate the fix.
Fixes #320.
=> AN-85 Fix bug where empty text in headings triggers an error

includes/apple-exporter/class-html.php, includes/apple-exporter/class-markdown.php, includes/apple-exporter/class-parser.php, includes/apple-exporter/components/class-body.php, includes/apple-exporter/components/class-byline.php, includes/apple-exporter/components/class-cover.php, includes/apple-exporter/components/class-facebook.php, includes/apple-exporter/components/class-gallery.php, includes/apple-exporter/components/class-heading.php, includes/apple-exporter/components/class-instagram.php, includes/apple-exporter/components/class-intro.php, includes/apple-exporter/components/class-quote.php, includes/apple-exporter/components/class-title.php, includes/apple-exporter/components/class-tweet.php, tests/apple-exporter/components/test-class-body.php
* Add sanity checks to components to prevent empty text nodes from registering JSON.
* Add filter to the HTML parser to remove empty tags.
* Add sanity checks to the Markdown parser to not add empty text.
* Add handling for nonbreaking spaces.
* Add tests for empty content handling.
Fixes #365
=> AN-91 Prevent empty text nodes from being added

admin/apple-actions/index/class-push.php
* If the skip_post filter is triggered, explain that the filter was the reason why the post was skipped, and include the post ID.
* If the post was not updated because it is already in sync, explain that to the user, and include the post ID.
Fixes #83
=> AN-118 If a post push is skipped, explain why

includes/apple-exporter/class-exporter.php, tests/admin/apple-actions/index/test-class-push.php
Over the past several releases, enhancements have been made to better identify and fix problems with content that would cause issues upon pushing to Apple News. Therefore, the check for invalid Unicode character sequences is now not providing much value, and is inhibiting valid content (including emoji) from being pushed to Apple News. This PR removes the check for invalid Unicode character sequences, and updates tests to reflect this change.
Fixes #404
=> AN-104 Remove overzealous check for invalid Unicode sequences

admin/class-admin-apple-index-page.php, admin/class-admin-apple-news.php, admin/partials/metabox_publish.php, admin/partials/page_single_push.php, admin/settings/class-admin-apple-settings-section-advanced.php, includes/apple-exporter/builders/class-metadata.php, includes/apple-exporter/class-settings.php, includes/class-apple-news.php, tests/apple-exporter/builders/test-class-metadata.php
* Adds a setting to allow users to opt in to using the Cover Art feature, rather than having it on by default, since it adds a significant number of image crops that are only useful if using this feature.
* Sets the setting to enabled for existing installations during upgrade, since there is not a good way to know whether a user has utilized this feature without running a very expensive postmeta query.
* Sets fallback messaging for the metabox and single push screens if the cover art feature is disabled, directing the user to the settings page to enable it.
Fixes #339
=> AN-113 Make cover art opt-in

includes/apple-exporter/components/class-facebook.php, tests/apple-exporter/components/test-class-facebook.php
* Adds handling for Facebook embeds in the form of `<fb:post href="url">`.
* Adds tests to cover the new format.
Fixes #388
=> AN-111 Add WordPress.com/OpenGraph Facebook Embeds Handler

admin/settings/class-admin-apple-settings-section-advanced.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/components/class-heading.php, includes/apple-exporter/components/class-quote.php, tests/admin/apple-actions/index/test-class-export.php, tests/apple-exporter/components/test-class-body.php, tests/apple-exporter/components/test-class-heading.php, tests/apple-exporter/components/test-class-quote.php
* Set default setting for `html_support` to be `yes`.
* Update language describing the setting, indicating that it is the preferred output format.
* Update `Heading` and `Quote` components to support HTML.
* Update tests to reflect these changes.
Fixes #448
=> AN-102 Make HTML the default output format

admin/apple-actions/class-action.php, admin/apple-actions/index/class-push.php, admin/apple-actions/index/class-section.php, admin/class-admin-apple-bulk-export-page.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-json.php, admin/class-admin-apple-news.php, admin/class-admin-apple-sections.php, admin/partials/page-sections.php, admin/settings/class-admin-apple-settings-section.php, includes/apple-exporter/builders/class-component-layouts.php, includes/apple-exporter/builders/class-component-text-styles.php, includes/apple-exporter/builders/class-components.php, includes/apple-exporter/builders/class-metadata.php, includes/apple-exporter/class-component-spec.php, includes/apple-exporter/class-theme.php, includes/apple-exporter/components/class-component.php, includes/class-apple-news.php
Addresses `PSR2.ControlStructures.SwitchDeclaration.TerminatingComment`.
Addresses `Squiz.Commenting.FunctionComment.ExtraParamComment`.
Addresses `Squiz.Commenting.FunctionComment.InvalidNoReturn`.
Addresses `Squiz.Commenting.FunctionComment.MissingParamTag`.
Addresses `Squiz.Commenting.FunctionComment.ParamCommentFullStop`.
Addresses `Squiz.Commenting.FunctionComment.ParamNameNoMatch`.
Addresses `Squiz.Commenting.FunctionComment.SpacingAfterParamType`.
Addresses `Squiz.Commenting.FunctionCommentThrowTag.Missing`.
Addresses `Squiz.Commenting.VariableComment.Missing`.
Addresses `Squiz.Operators.IncrementDecrementUsage.NoBrackets`.
Addresses `Squiz.PHP.DisallowMultipleAssignments.Found`.
Addresses `Squiz.Scope.MethodScope.Missing`.
=> AN-132 Fix remaining phpcs errors not specific to WordPress

admin/apple-actions/index/class-push.php, admin/class-admin-apple-async.php, admin/class-admin-apple-bulk-export-page.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-json.php, admin/class-admin-apple-themes.php, admin/partials/cover-art.php, admin/partials/page-json.php, admin/partials/page-sections.php, admin/settings/class-admin-apple-settings-section-api.php, includes/apple-exporter/class-component-spec.php, includes/apple-exporter/class-theme.php, includes/apple-exporter/components/class-heading.php, includes/apple-push-api/class-mime-builder.php
* Addresses `WordPress.WP.I18n.MissingTranslatorsComment`.
* Addresses `WordPress.WP.I18n.TextDomainMismatch`.
* Addresses `WordPress.WP.I18n.MissingArgDomain`.
=> AN-132 Fix i18n phpcs errors

.travis.yml, admin/apple-actions/index/class-delete.php, admin/apple-actions/index/class-export.php, admin/class-admin-apple-bulk-export-page.php, admin/class-admin-apple-index-page.php, admin/class-admin-apple-json.php, admin/class-admin-apple-meta-boxes.php, admin/class-admin-apple-news-list-table.php, admin/class-admin-apple-notice.php, admin/class-admin-apple-sections.php, admin/class-admin-apple-themes.php, admin/settings/class-admin-apple-settings-section.php, includes/apple-exporter/builders/class-components.php, includes/apple-exporter/class-settings.php, includes/apple-exporter/class-theme.php, includes/apple-exporter/components/class-tweet.php, tests/admin/test-class-admin-apple-meta-boxes.php, tests/admin/test-class-admin-apple-sections.php, tests/admin/test-class-admin-apple-themes.php
* Addresses `WordPress.CSRF.NonceVerification.NoNonceVerification`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.MissingUnslash`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized`.
* Addresses `WordPress.XSS.EscapeOutput.OutputNotEscaped`.
* Addresses `WordPress.PHP.YodaConditions.NotYoda`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_update_user_meta`.
* Addresses `WordPress.VIP.ValidatedSanitizedInput.InputNotValidated`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_delete_user_meta`.
* Addresses `WordPress.VIP.RestrictedFunctions.user_meta_get_user_meta`.
* Addresses `WordPress.VIP.FileSystemWritesDisallow.file_ops_delete`.
* Addresses `WordPress.Variables.GlobalVariables.OverrideProhibited`.
Fixes #96
=> AN-132 Miscellaneous WordPress phpcs Error Fixes

admin/class-admin-apple-meta-boxes.php
The `save_post` action was being used to perform a publish action on
all post types, without regard to whether the post type was registered
with Publish to Apple News or not. Therefore, when a `save_post` action
triggered for a post type that was not registered to PTAN, the nonce
verification check failed, since the metabox was not being displayed
and therefore the nonce was not being generated. This commit modifies
the behavior of the `save_post` action to register separate `save_post`
action hooks for each supported post type.
=> Bugfix: Tie the `save_post` action only to registered PTAN post types

includes/apple-exporter/class-exporter-content.php, tests/apple-exporter/test-class-exporter-content.php
Fixes #559.
- Decode HTML entities in URLs extracted from HTML src attributes.
=> Decode HTML entities in URLs from src attributes

admin/partials/metabox-publish.php, admin/partials/page-single-push.php
This updates the description that appears below the section selection checkboxes to more accurately explain the current behavior -- "If none are selected, it will be published to the default section."
=> Updated section selection description to reflect current behavior.

admin/class-admin-apple-meta-boxes.php, admin/class-admin-apple-post-sync.php, admin/partials/metabox_publish.php, admin/partials/page_single_push.php, assets/js/meta-boxes.js
Backporting selective publish UI to 1.3.0, see also #591
=> Proposed v1.3.1

includes/apple-exporter/class-exporter.php, includes/apple-exporter/class-html.php, tests/apple-exporter/components/test-class-body.php, tests/apple-exporter/test-class-exporter.php
Closes: https://alleyinteractive.atlassian.net/browse/AN-146
Potentially closes: #615, #561, #585, #604
- Adds support or the `à` character, and french characters showng below #615:
`Les naïfs ægithales hâtifs pondant a Noël où il gèle sont sûrs d'être déçus en voyant leurs drôles d'œufs abîmés. aÀâÂèÈéÉêÊëËîÎïÏôÔùÙûÛüÜÿŸçÇœŒ€æÆ
`
- Prevents elements in the Classic Editor or Gutenberg editor with the `à` character from throwing an undefined index error #561, and provides output instead of an empty array for those elements #585.
- Fixes issues with non-escaped Unicode characters like `&` #604 causing issues with JSON output.
- Renders French and English characters in Apple News reader:
=> An 146 unicode character support

.gitignore, admin/apple-actions/index/class-export.php, includes/apple-exporter/class-component-factory.php, includes/apple-exporter/components/class-component.php, includes/apple-exporter/components/class-embed-web-video.php, includes/apple-exporter/components/class-facebook.php, includes/apple-exporter/components/class-image.php, tests/admin/apple-actions/index/test-class-export.php
Closes #599, #597, #596, #594
Also Closes: https://alleyinteractive.atlassian.net/browse/AN-154
- Fixes Facebook embeds, relies on WordPress to filter "success" embeds, and accommodate all mobile, short link and full facebook URLs. 
- Replaced multiple Facebook REGEX strings with single catch-all.
- Fixes YouTube embeds and new Gutenberg embed structure.
- Adds function to check for Gutenberg embed structure.
- Checks for excerpt before outputting the excerpt.
Includes images and article.json for Gutenberg and the Classic Editor (rename article.json to test).
[apple-news-test.zip](https://github.com/alleyinteractive/apple-news/files/3153274/apple-news-test.zip)
NOTE: There will be image width warnings because the images used were small.
=> AN-154 fix embeds

assets/js/pluginsidebar/components/sidebar/index.js, includes/REST/apple-news-get-settings.php
Closes: #614 
Completes: https://alleyinteractive.atlassian.net/browse/AN-147
- Adds "Assign sections by category" checkbox, and assigned/removes data as necessary.
- Fixes several `string`/`JSON.parse`-related errors.
- Allows "sections" post meta to be `null` instead of an empty array to appease the PHP side of the plugin/publishing.
- Updates the "settings" endpoint to include a boolean based on the value of (or not of) `apple_news_section_taxonomy_mappings`. If true, there are sections saved in post meta and the default is not to "Assign sections by category".
=> AN-147 publish to multiple sections

admin/class-admin-apple-news.php, admin/class-admin-apple-notice.php, apple-news.php, assets/js/pluginsidebar/components/sidebar/index.js, includes/REST/apple-news-delete.php, includes/REST/apple-news-get-settings.php, includes/REST/apple-news-publish.php, includes/REST/apple-news-update.php, includes/REST/apple-news-user-can-publish.php
* Adds Publish, Update, and Delete buttons if the settings for "automatically publish/update/delete in Apple News if published/updated/deleted in WordPress" are set to "no."
* Adds permissions checks to only show the buttons if users are authorized to use them.
* Creates new REST endpoints to handle these actions.
* Adds a handler for if a user closes and un-favorites the Apple News PluginSidebar to be able to get it back without hacking localStorage.
* Augments the list of settings returned by the API to return all non-sensitive settings for logged-in users.
=> AN-166 Add Publish, Update, and Delete Buttons

admin/class-admin-apple-meta-boxes.php
Fixes #622 
Filters wp_refresh_nonces to refresh the apple_news_nonce to prevent data loss after re-authenticating an expired session.
=> Refreshing meta box nonce after re-authenticating following a wp_auth_check()

includes/apple-exporter/class-component-factory.php, includes/apple-exporter/components/class-soundcloud.php, includes/apple-exporter/components/class-spotify.php, includes/apple-exporter/components/class-wp-embed.php, tests/apple-exporter/components/test-class-soundcloud.php, tests/apple-exporter/components/test-class-spotify.php, tests/apple-exporter/components/test-class-wp-embed.php
Closes: https://alleyinteractive.atlassian.net/browse/AN-176 formerly AN-169
- Adds Gutenberg support for WP Embeds, Spotify Embeds, and SoundCloud Embeds.
- Adds unit tests for each.
- Backward compatibility with the Classic Editor
=> AN-169 Additional Gutenberg Embeds Support

admin/class-admin-apple-meta-boxes.php, admin/class-admin-apple-post-sync.php, apple-news.php, assets/js/pluginsidebar/components/sidebar/index.js, includes/class-apple-news.php, readme.txt
Closes: #666, #669, #670
- Adds check for some 5.0.0+ functions before attempting to execute.
- Adds fallback and additional checks for sidebarPlugin retrieval of post meta.
- Only makes REST request for post save when Gutenberg is enabled.
- Enqueues block editor scripts with `enqueue_block_editor_assets`.
- Version bump to 2.0.2.
- Updates changelog.
=> AN-182 version 201 bugs

admin/apple-actions/index/class-push.php, admin/class-admin-apple-post-sync.php, tests/admin/apple-actions/index/test-class-push.php
* Moves all publishing back to the `save_post` hook rather than having a separate workflow for Gutenberg.
* Introduces a checksum system to prevent double publishing of the same content as a more robust check than date in `is_post_in_sync`.
* Adds a test for the behavior of `is_post_in_sync`.
=> AN-183 Hotfix—autopublishing not working on some platforms

apple-news.php, assets/js/pluginsidebar/components/sidebar/index.js, includes/class-apple-news.php, readme.txt
- Added fallback for the `coverArt` check to proceed even if it's an empty object.
- Added a check against the active post types in the Settings field before initializing the `pluginSidebar` scripts.
- Version bump
- Changelog update.
=> Editor Unexpected Error Fix

assets/js/pluginsidebar/components/sidebar/index.js, assets/js/pluginsidebar/index.js, includes/class-apple-news.php
* Re-split block editor and admin script enqueue
* Add safety checks for multi-level destructuring
* Don't register the PluginSidebar at all if the wp object doesn't exist or if registerSidebar isn't defined
=> AN-198 Additional JavaScript safety checks

includes/class-apple-news.php
Error came up when the plugin is loaded through VIP's plugin loader and has no settings initialized.
=> Ensure that an array is always passed as an array

admin/partials/metabox-publish.php, admin/partials/page-single-push.php, assets/js/pluginsidebar/components/sidebar/index.js
Per #693 the error message about paid content is confusing if you aren't aware that Apple requires the channel to be approved for paid content before attempting to use the `isPaid` flag. This PR adds an explanation to all areas where the flag can be configured to hopefully head off support requests when users attempt to apply the flag on channels that don't support paid content.
A future enhancement could query the channel to see if paid content is allowed, if possible, before displaying the checkbox as an option to the user at all.
=> Add warning for use of isPaid flag to prevent confusion on error

includes/apple-exporter/components/class-image.php, tests/apple-exporter/components/test-class-image.php
This update will allow the following `<img />` and caption markup:
```
<figure class="wp-caption">
<figcaption class="wp-caption-text">
Caption content.
<span class="credit">Credit</span>
</figcaption>
</figure>
```
get output correctly in the JSON.
Also reference: https://github.com/alleyinteractive/apple-news/issues/692
=> add condition to output an image caption housed in a figure element with a wp-caption CSS css selector

includes/apple-push-api/request/class-request.php
Fix the display message in posts  in case you don't enter a correct API:
```
object(stdClass)#4114 (1) { ["code"]=> string(17) "API_KEY_NOT_FOUND" }
```
=> Patch fix undefined stdClass error message API_KEY_NOT_FOUND

includes/apple-exporter/components/class-embed-generic.php, tests/apple-exporter/components/test-class-embed-generic.php
5.4.0 adds TikTok as a supported embed and the generic embed component doesn't match the URL for TikTok correctly or list it as a provider.
=> Adding TikTok compatibility to the generic embed component

includes/apple-exporter/components/class-facebook.php, tests/apple-exporter/components/test-class-facebook.php
If you have something that looks like a Facebook URL in your HTML, for example:
```html
Visit us at <a href="https://www.facebook.com/alleyinteractive/">facebook.com/alleyinteractive</a>!
```
The Facebook matcher will overzealously assume that `facebook.com/alleyinteractive` is a Facebook oEmbed and will convert the entire block to a Facebook component. This fix a) confirms the issue via a unit test and b) fixes the issue, validating the fix via the unit test.
The core of the issue here is that the Facebook URL matcher is *very* permissive, so we want to make sure that when matching against the value of a node for just a URL that the only thing that is being matched is an actual URL, which is the case when WordPress is embedding something via oEmbed - the only thing on the line is the URL …
=> Fix for Facebook URLs contained in-text incorrectly getting converted to Facebook components
